### ISSUE TITLE
Error: Could not find or load main class io.coinswap.client.Main

### ISSUE THREAD

**Issue by peerchemist** [mappum/mercury#2]
I get this error on startup, using java-8-openjdk on Linux.

**Comment by willyfromtheblock** [comment]
I can second that with 

java version "1.6.0_23"
Java(TM) SE Runtime Environment (build 1.6.0_23-b05)
Java HotSpot(TM) Client VM (build 19.0-b09, mixed mode, sharing)

on windows

**Comment by willyfromtheblock** [comment]
I did get mercury running!

 java -jar " Mercury Wallet.jar"

did it for me

 ~/mercury $ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Honestly: It looks FANTASTIC!

**Comment by mappum** [comment]
I haven't looked into properly bundling it in a way that is easy to redistribute (an installer, OSX .app, etc.), so sorry that it's just a bunch of .jars right now. I'll look for a better solution then it should resolve this issue.

> Honestly: It looks FANTASTIC!

Thanks! :)

**Comment by mappum** [comment]
For now, this error can be fixed by updating to Java 8.

**Comment by mappum** [comment]
Now there are binaries built for each platform. This problem shouldn't be encountered anymore. :)

**Comment by dmp1ce** [comment]
I'm still experiencing this issue. I'm on Arch Linux with JDK8.

```
$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
$ java -jar "MercuryWallet-0.0.2.jar" 
Error: Could not find or load main class io.coinswap.client.Main
```

**Comment by mechanicrealization** [comment]
I am getting the exact same result as @peerchemist and @dmp1ce. Attempted on Linux with OpenJDK 8 JRE using the Mercury binary.

```
$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
$ java -jar "MercuryWallet-0.0.2.jar"
Error: Could not find or load main class io.coinswap.client.Main
```

**Comment by IIIIIHIIIII** [comment]
Installing java-openjfx fixed this for me.

sudo pacman -S java-openjfx

**Comment by dmp1ce** [comment]
I created a package on the AUR for Arch users.

https://aur.archlinux.org/packages/mercuryex/
